services:
  - type: web
    name: academy-frontend
    runtime: static
    repo: https://github.com/rmbo0o/academy-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
